
version: '2'

services:
  www:
    image: nginx:1.13-alpine
    networks:
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=www.${APP_SITE}"
      - "traefik.frontend.rule=Host:www.${APP_SITE}"
    volumes:
      - .:/usr/share/nginx:ro

  redirect:
    image: nginx:1.13-alpine
    networks:
      - web
    restart: always
    depends_on:
      - www
    environment:
    - SERVER_REDIRECT=www.${APP_SITE}
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:${APP_SITE}"
    volumes:
    - ./nginx_redirect.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  web:
    external:
      name: ${DCAPE_NET}
